import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { Nav } from "@/components/Nav";

import { TopNavBar } from "@/components/TopNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const theme = cookies().get("theme");

    return (
        <html lang="en" className={theme?.value}>
            <body
                className={`${inter.className} relative  mx-auto flex flex-col justify-center items-center min-h-screen w-screen  overflow-x-hidden no-scrollbar `}
            >
                <TopNavBar />
                {children}

                <Nav />
            </body>
        </html>
    );
}
